services:
  YesPlayMusic:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: yesplaymusic
    container_name: YesPlayMusic
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - 19980:80
    # restart: always
    # environment:
    #   - NODE_TLS_REJECT_UNAUTHORIZED=0

