services:
  YesPlayMusic:
    build:
      context: .
    image: yesplaymusic
    container_name: YPMContainer
    ports:
      - 12321:80
    restart: always
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: 0
    links:
      - UnblockNeteaseMusic:unm

  UnblockNeteaseMusic:
    image: pan93412/unblock-netease-music-enhanced
    container_name: UNMContainer
    environment:
      NODE_ENV: production
    expose:
      - 8080
    restart: always
    command: -o ytdlp kuwo kugou
